'use client';
import {useState} from 'react';
const fields=[['ca','CA net enregistré','#237461'],['buy','Achats & sous-traitance','#ce8c7a'],['labor','Rémunérations enregistrées','#c3a35f'],['charges','Autres charges','#8e9caa']] as const;
export interface OperationsRow {month:string; ca:number; other:number; buy:number; labor:number; charges:number; previous?:number|null}
type Row=OperationsRow;const gross=(r:Row)=>r.ca+r.other-r.buy;const result=(r:Row)=>gross(r)-r.labor-r.charges;const euro=(n:number)=>`${n.toLocaleString('fr-BE')} €`;
export function OperationsChart({data,rangeMonths}:{data:OperationsRow[];rangeMonths?:number}){
 const [period,setPeriod]=useState(12),[hidden,setHidden]=useState<string[]>([]),[focus,setFocus]=useState<number|null>(null),[table,setTable]=useState(false),[large,setLarge]=useState(false);
 const rows=data.slice(-(rangeMonths ?? period));const on=(k:string)=>!hidden.includes(k);const toggle=(k:string)=>setHidden(v=>v.includes(k)?v.filter(x=>x!==k):[...v,k]);
 const sum=(f:(r:Row)=>number)=>rows.reduce((a,r)=>a+f(r),0);const selected=focus===null?null:rows[Math.min(focus,rows.length-1)];
 const width=850,left=58,bottom=320,top=15;
 const max=Math.max(1,...rows.map(r=>r.ca+r.other),...rows.map(result))*1.1;
 const min=Math.min(-1,...rows.map(r=>-(r.buy+r.labor+r.charges)),...rows.map(result))*1.1;const y=(n:number)=>bottom-(n-min)/(max-min)*(bottom-top);const step=(width-left-15)/rows.length;
 return <div className={large?'operations-expanded':'operations-body'}><div className="operations-toolbar">{rangeMonths===undefined&&<label>Période<select value={period} onChange={e=>{setPeriod(Number(e.target.value));setFocus(null)}}><option value={12}>12 mois glissants</option><option value={6}>6 derniers mois</option><option value={3}>3 derniers mois</option></select></label>}<button className="btn" onClick={()=>setLarge(!large)}>{large?'Réduire':'Agrandir'}</button></div>
 <div className="operations-totals">{[['Produits · HT',sum(r=>r.ca+r.other)],['Coûts d’exploitation',sum(r=>r.buy+r.labor+r.charges)],['Résultat enregistré',sum(result)]].map(([label,n])=><div key={label}><span>{label}</span><strong>{euro(Number(n))}</strong></div>)}</div>
 <div className="operations-canvas"><svg viewBox="0 0 850 365" role="img" aria-label="Produits positifs, coûts négatifs, marge brute et résultat. Tableau accessible en dessous.">{[min,min/2,0,max/2,max].map(n=><g key={n}><line x1={left} x2={width-15} y1={y(n)} y2={y(n)} stroke={n===0?'#778c84':'var(--line)'} strokeWidth={n===0?1.5:1}/><text x={left-8} y={y(n)+4} fontSize="12" textAnchor="end" fill="var(--ink-3)">{Math.round(n/1000)} k</text></g>)}
 {rows.map((r,i)=>{let up=0,down=0;return <g key={r.month}>{fields.filter(([key])=>on(key)).map(([key,label,color],j)=>{const signed=key==='ca'?r[key]:-r[key];const positive=signed>=0;const base=positive?up:-down;const end=base+signed;if(positive)up+=signed;else down-=signed;return <rect key={key} x={left+(i+.2)*step} y={Math.min(y(base),y(end))} width={step*.6} height={Math.abs(y(base)-y(end))} fill={color} opacity={focus===null||focus===i?1:.5}/>})}<text x={left+(i+.5)*step} y="347" fontSize="13" textAnchor="middle" fill="var(--ink-3)">{r.month}</text></g>})}
 {on('gross')&&<polyline points={rows.map((r,i)=>`${left+(i+.5)*step},${y(gross(r))}`).join(' ')} fill="none" stroke="#92ad9e" strokeWidth="2" strokeDasharray="5 4"/>}{on('result')&&<g><polyline points={rows.map((r,i)=>`${left+(i+.5)*step},${y(result(r))}`).join(' ')} fill="none" stroke="#173f34" strokeWidth="2.5"/>{rows.map((r,i)=><circle key={i} cx={left+(i+.5)*step} cy={y(result(r))} r={focus===i?5:3} fill="white" stroke="#173f34" strokeWidth="2"/>)}</g>}
 {rows.map((r,i)=><rect key={r.month} x={left+i*step} y={top} width={step} height={bottom-top} fill="transparent" role="button" tabIndex={0} aria-label={`${r.month}, résultat ${euro(result(r))}`} onMouseEnter={()=>setFocus(i)} onFocus={()=>setFocus(i)} onClick={()=>setFocus(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')setFocus(i)}}/>)}</svg></div>
 <div className="operations-legend">{[...fields,['result','Résultat','#173f34'],['gross','Après achats','#92ad9e']].map(([key,name,color])=><button key={key} className={!on(key)?'off':''} aria-pressed={on(key)} onClick={()=>toggle(key)}><i style={{background:color}}/>{name}</button>)}</div>
 <div className="dashboard-chart-detail" aria-live="polite">{selected?<><strong>{selected.month}</strong><span>Produits : <b>{euro(selected.ca+selected.other)}</b></span><span>Coûts : <b>{euro(selected.buy+selected.labor+selected.charges)}</b></span><span>Résultat : <b>{euro(result(selected))}</b></span></>:<span>Touchez un mois pour lire les montants. Cliquez sur la légende pour masquer des postes.</span>}</div>
 <div className="dashboard-chart-foot"><p className="muted">Grand livre · HT · par date de pièce, mois courant inclus et provisoire. Résultat enregistré = CA net − charges enregistrées. Les rémunérations proviennent des achats, sans ajout des coûts estimés des pointages. Les pièces manquantes ne sont pas estimées. Ce n’est ni le solde bancaire ni un résultat comptable certifié. Les totaux et courbes conservent tous les postes, même masqués.</p><button className="btn" onClick={()=>setTable(!table)}>{table?'Masquer':'Voir'} les données</button></div>
 {table&&<div className="tbl-wrap"><table className="tbl"><thead><tr><th>Mois</th>{fields.map(([key,label])=><th key={key}>{label}</th>)}<th>Après achats</th><th>Résultat</th></tr></thead><tbody>{rows.map(r=><tr key={r.month}><td>{r.month}</td>{fields.map(([key])=><td key={key}>{euro(r[key])}</td>)}<td>{euro(gross(r))}</td><td>{euro(result(r))}</td></tr>)}</tbody></table></div>}</div>
}
