/* Isolated API fixtures for the REAL application screens. No production connection. */
import {officeFixtures} from './office-fixtures';
import {taskFixtures} from './task-fixtures';
import {timeFixtures,ensureTimeEntries} from './time-fixtures';
import {threadFixtures,sharedMedia} from './thread-fixtures';
import {computeWorksiteMargin,computeDocTotals,CRM_STAGES,requestBriefInput} from '@jjd/shared';
const key='jjd-business-fixtures-v1';
const contact={id:'supplier1',type:'supplier',name:'Fournisseur Démo',email:'fournisseur@example.test',phone:null,onAccount:true,customerNumber:'DEMO'};
const seeds:any={stock:[['s1','Enduit de finition 25 kg','sac',12,'filler-bags.png'],['s2','Film de protection','rouleau',8,null],['s3','Ruban de masquage','rouleau',24,null]].map(([id,name,unit,qty,img],i)=>({id,name,unit,qty,ref:`JJD-00${i+1}`,brand:null,model:null,category:'Finitions',minQty:5,avgCost:18,value:Number(qty)*18,low:false,active:true,photoUrl:img?`/demo/jjd/${img}`:null,photoThumbUrl:img?`/demo/jjd/${img}`:null,description:'Article de démonstration',location:'A-02',units:[],barcodes:[{id:`bc${i}`,code:`JJD-00${i+1}`,unitName:null}],suppliers:[{id:`sp${i}`,contactId:'supplier1',contact,supplierRef:`REF-${i}`,price:18,unitName:null,preferred:true}]})),preps:[{id:'prep1',ref:'PREP-024',worksiteId:'w1',status:'to_prepare',neededOn:'2026-10-01',note:'À emporter au départ du dépôt',lines:[{id:'pl1',stockItemId:'s1',qty:16,pickedQty:0,unitName:null},{id:'pl2',stockItemId:'s2',qty:3,pickedQty:0,unitName:null}]}],orders:[{id:'po1',ref:'CF-041',contactId:'supplier1',worksiteId:'w1',status:'ordered',expectedOn:'2026-09-30',orderedOn:'2026-09-28',note:'Complément pour la préparation PREP-024',supplierRef:'DEMO-FOUR-041',lines:[{id:'pol1',stockItemId:'s1',qty:10,receivedQty:0,price:18,unitName:null}]}],moves:[],buildingEdits:{},tasks:{},threads:{}};
let state:any;try{state=JSON.parse(localStorage.getItem(key)||'null')}catch{}if(!state)state=structuredClone(seeds);
const save=()=>localStorage.setItem(key,JSON.stringify(state));
const uid=()=>crypto.randomUUID();
const need=(x:any)=>{if(!x)throw Error('Élément introuvable dans cet aperçu.');return x};
export function resetBusiness(){localStorage.removeItem(key)}
export function businessApi(path:string,method:string,b:any,db:any,people:any[]):any{
 const u=new URL(path,'https://demo.invalid'),p=u.pathname,parts=p.split('/');
 const threadResult=threadFixtures(p,method,b,state,db,people,save);if(threadResult!==undefined)return threadResult;
 const timeResult=timeFixtures(p,method,b,u,state,db,people,save);if(timeResult!==undefined)return timeResult;
 const taskResult=taskFixtures(p,method,b,u,state,db,people,save);if(taskResult!==undefined)return taskResult;
 if(p.startsWith('/api/worksites/')&&p.includes('/thread')&&method!=='GET'&&!(method==='POST'&&p.endsWith('/messages')))throw Error('Le partage de fichiers et les actions avancées ne sont pas connectés dans cet aperçu. Aucun message client envoyé.');
 const office=officeFixtures(p,method,b,u,state,db,people,save);if(office!==undefined)return office;
 const ws=(id:string)=>db.worksites.find((w:any)=>w.id===id);
 if(!state.expenses)state.expenses=db.worksites.map((w:any,i:number)=>({id:'exp'+i,date:'2026-09-28',dueDate:'2026-10-28',direction:'purchase',docNumber:'ACH-DEMO-'+i,supplier:'Fournisseur Démo',supplierName:'Fournisseur Démo',contactId:'supplier1',categoryRaw:'Matériaux',categoryCode:'materials',categoryLabel:'Matériaux',worksiteId:w.id,worksite:w,vehicleId:null,vehicle:null,ht:2300+i*500,vatRecup:(2300+i*500)*.21,ttc:(2300+i*500)*1.21,vatRate:.21,notes:'Facture de démonstration',paymentStatus:i%2?'unpaid':'paid',paid:i%2===0,paidOn:null,hasPdf:false,editable:true,source:'manual',linkedInvoiceId:null,linkedInvoice:null,_count:{bordereaux:0}}));
 if(!state.portalPeopleV1){state.contacts??=[];for(let i=0;i<4;i++)state.contacts.push({id:'portal-person-'+i,name:['Alex Exemple','Camille Démo','Sophie Exemple','Morgan Démo'][i],type:'client',kind:'individual',phone:'',email:'contact'+i+'@example.test'});state.portalPeopleV1=true;save();}
 const buildings=()=>db.worksites.filter((w:any)=>w.building).map((w:any,i:number)=>({id:w.building.id,name:w.building.name,kind:i===2?'developer':'acp',address:w.address,postalCode:w.postalCode,city:w.city,lotCount:i===2?12:22,photoUrl:w.building.photoThumbUrl,photoThumbUrl:w.building.photoThumbUrl,syndic:i===0||i===3?{id:'syndic1',name:'Syndic Démo',phone:null,email:'syndic@example.test'}:null,promoter:i===2?{id:'promoter1',name:'Promoteur Démo',phone:null,email:null}:null,contacts:[{id:'bc-'+i,contactId:'portal-person-'+i,role:'concierge',name:'Alex Exemple',phone:null,email:'contact@example.test',note:'Accès sur rendez-vous',contact:null}],linkedContacts:[],units:[{id:'unit-'+i,label:i===2?'Lot 12':'Appartement 3B',floor:'3',door:null,contactId:null,contact:null,occupantName:'Occupant Démo',occupantPhone:null,occupantEmail:null,occupantKind:'tenant',note:null}],...state.buildingEdits[w.building.id],worksites:db.worksites.filter((v:any)=>v.building?.id===w.building.id).map((v:any)=>({...v,documents:[]})),_count:{worksites:db.worksites.filter((v:any)=>v.building?.id===w.building.id).length}})).filter((v:any,i:number,all:any[])=>all.findIndex(b=>b.id===v.id)===i).concat((state.extraBuildings||[]).map((b:any)=>({...b,...state.buildingEdits[b.id],worksites:db.worksites.filter((w:any)=>w.building?.id===b.id).map((w:any)=>({...w,documents:[]})),_count:{worksites:db.worksites.filter((w:any)=>w.building?.id===b.id).length}})));
 const orderView=(o:any)=>({...o,contact,worksite:ws(o.worksiteId)||null,createdAt:'2026-09-29',lines:o.lines.map((l:any)=>({...l,stockItem:need(state.stock.find((s:any)=>s.id===l.stockItemId))})),lineCount:o.lines.length,doneLines:o.lines.filter((l:any)=>l.pickedQty>=l.qty).length,receivedLines:o.lines.filter((l:any)=>l.receivedQty>=l.qty).length,totalHt:o.lines.reduce((s:number,l:any)=>s+l.qty*(l.price||0),0)});
 const movement=(item:any,n:number,reason:string,worksiteId?:string)=>{state.moves.unshift({id:uid(),type:n>=0?'in':'out',qty:Math.abs(n),enteredQty:Math.abs(n),enteredUnit:item.unit,stockItem:item,worksite:ws(worksiteId||''),contact:null,createdBy:{email:'demo@example.test'},createdAt:new Date().toISOString(),note:reason,unitCost:item.avgCost});item.qty+=n;item.value=item.qty*item.avgCost;item.low=item.qty<item.minQty};
 const contacts=()=>[...db.worksites.map((w:any)=>({...w.client,type:'client',email:'client@example.test',city:w.city,vat:null,address:w.address})).filter((c:any)=>c.id),contact,...buildings().map((b:any)=>({id:b.id,name:b.name,city:b.city,type:'client',kind:b.kind})),...(state.contacts||[])].filter((c:any,i:number,all:any[])=>all.findIndex(x=>x.id===c.id)===i).filter((c:any)=>!(state.deletedContacts||[]).includes(c.id)).map((c:any)=>({...c,...state.contactEdits?.[c.id],_count:{worksites:db.worksites.filter((w:any)=>w.client?.id===c.id).length}}));
 const currentPerson=(row:any)=>{const person=row.contactId?contacts().find((c:any)=>c.id===row.contactId):null;return person?{...row,contact:person,name:person.name,phone:person.phone??null,email:person.email??null}:row;};
 if(p.startsWith('/preview-portal')){
  const route=p.replace('/preview-portal','');const promoter=localStorage.getItem('jjd-preview-client-profile')==='promoter';
  const allowed=buildings().filter((b:any)=>promoter?b.promoter:!!b.syndic);const ids=new Set(allowed.map((b:any)=>b.id));
  const visible=db.worksites.filter((w:any)=>ids.has(w.building?.id)).map((w:any)=>({id:w.id,ref:w.ref,title:w.title,status:w.status,statusLabel:w.status==='on_hold'?'En observation':w.status==='lead'?'Demande reçue':'En cours',priority:w.priority,priorityLabel:w.priority==='urgent'?'Urgent':'Normal',address:w.address,building:{id:w.building.id,name:w.building.name},manager:'Julien',updatedAt:'2026-09-30T08:00:00Z',startedOn:null,endedOn:null,description:w.description||'Travaux et suivi du dossier',nextStep:w.status==='on_hold'?'Contrôler le séchage avant la remise en peinture.':'Confirmer le prochain passage.'}));
  const portfolio=allowed.map((b:any)=>({...b,syndic:b.syndic?.name||null,manager:'Julien',open:visible.filter((w:any)=>w.building.id===b.id).length,worksites:visible.filter((w:any)=>w.building.id===b.id)}));
  if(route==='/buildings')return {buildings:portfolio};
  if(route==='/interventions')return {items:visible.filter((w:any)=>!u.searchParams.get('q')||w.title.toLowerCase().includes(u.searchParams.get('q')!.toLowerCase())).filter((w:any)=>!u.searchParams.get('status')||u.searchParams.get('status')==='open'||w.status===u.searchParams.get('status'))};
  if(route==='/dashboard')return {greeting:{name:promoter?'Promoteur Démo':'Syndic Démo',isSyndic:!promoter,access:'full'},singleProject:null,portfolio,kpis:{buildings:portfolio.length,interventionsActive:visible.length,quotesToValidate:0,urgent:visible.filter((w:any)=>w.priority==='urgent').length},urgentItems:[],recentInterventions:visible.map((w:any)=>({...w,building:w.building.name,invoiceStatus:null})),weekPlanning:{days:[]},quotesToValidate:[],recentDocuments:[]};
  if(route==='/planning')return {items:db.events.filter((e:any)=>visible.some((w:any)=>w.id===e.worksite?.id)).map((e:any)=>({...e,worksiteId:e.worksite.id,worksiteRef:e.worksite.ref,worksiteTitle:e.worksite.title,building:e.worksite.building?.name,people:e.assignments.map((a:any)=>a.person.displayName),team:null}))};
  if(route==='/requests/context'){const building=need(allowed.find((x:any)=>x.id===u.searchParams.get('buildingId')));const refs=[...(building.contacts||[]),...(building.units||[])];return {units:(building.units||[]).map((r:any)=>({label:r.label})),contacts:contacts().filter((c:any)=>refs.some((r:any)=>r.contactId===c.id)||c.linkedAcpId===building.id).map((c:any)=>({id:c.id,name:c.name,phone:c.phone||'',email:c.email||''})),worksites:building.worksites.map((w:any)=>({id:w.id,title:w.title,ref:w.ref}))};}
  if(route==='/requests'&&method==='GET')return {items:(state.opportunities||[]).filter((o:any)=>o.source==='portail'&&ids.has(o.acpId)).map((o:any)=>({id:o.id,title:o.title,reference:o.reference,building:allowed.find((x:any)=>x.id===o.acpId)?.name,createdAt:o.createdAt,statusLabel:o.stage==='new'?'Reçue · à examiner':o.stage==='lost'?'Clôturée':'En cours d’étude'}))};
  if(route==='/requests'&&method==='POST'){
    const building=need(allowed.find((x:any)=>x.id===b.buildingId));
    const brief=requestBriefInput.parse({...b.requestBrief,attachments:[]});
    const files=b.requestBrief?.attachments||[];if(files.length>8||files.some((f:any)=>f.mime!=='application/pdf'||!/^data:application\/pdf;base64,/.test(f.url)||f.url.length>2900000))throw Error('PDF invalide dans cet aperçu.');brief.attachments=files;
    const related=brief.relatedWorksiteId;if(related&&!building.worksites.some((w:any)=>w.id===related))throw Error('Dossier non accessible pour cet immeuble.');
    const refs=[...(building.contacts||[]),...(building.units||[])];
    for(const person of brief.contacts){if(person.contactId){const known=contacts().find((c:any)=>c.id===person.contactId&&(refs.some((r:any)=>r.contactId===c.id)||c.linkedAcpId===building.id));if(!known)throw Error('Contact non accessible.');Object.assign(person,{name:known.name,phone:known.phone||'',email:known.email||''});}}
    // Reuse seeded CRM data even when the portal is opened before the office.
    businessApi('/api/crm','GET',undefined,db,people);
    const existing=b.requestKey?state.opportunities.find((o:any)=>o.requestKey===b.requestKey&&o.acpId===building.id):null;if(existing)return {id:existing.id,reference:existing.reference};
    const id=uid(),reference='INT-DEMO-'+id.slice(-5).toUpperCase();
    state.opportunities.push({id,reference,requestKey:b.requestKey,title:b.title,source:'portail',acpId:building.id,stage:'new',urgent:b.urgency==='urgent',urgency:b.urgency,unitLabel:brief.units.map((x:any)=>x.label).join(', ')||b.unitLabel,note:b.details,problemType:b.problemType,requestBrief:brief,onSiteContactName:b.onSiteContactName,onSiteContactPhone:b.onSiteContactPhone,accessNotes:b.accessNotes,visitPreference:b.visitPreference,photos:(b.photos||[]).map((p:any)=>({...p,id:uid()})),createdAt:new Date().toISOString(),nextActionOn:new Date().toISOString(),nextActionNote:'Demande client · à examiner'});try{save();}catch{state.opportunities.pop();throw Error('Le stockage de la maquette est plein. Retirez quelques pièces jointes et réessayez ; le formulaire reste ouvert.');}return {id,reference};
  }
  if(route.startsWith('/worksites/')){const id=route.split('/')[2];const w=need(visible.find((w:any)=>w.id===id));const thread=id+'-client';state.threads[thread]??=[];if(method==='POST'&&route.endsWith('/messages')){state.threads[thread].push({id:uid(),body:b.body,kind:'text',authorName:'Client Démo',fromClient:true,createdAt:new Date().toISOString()});save();}const media=sharedMedia(state,id);return {worksite:w,manager:{name:'Julien',phone:null},quotes:[],invoices:[],photos:media.map((m:any)=>({id:m.id,url:m.fileUrl,thumbUrl:m.thumbUrl,caption:m.body,createdAt:m.createdAt,video:m.kind==='video'})),reports:[],messages:[...state.threads[thread],...media].sort((a:any,b:any)=>a.createdAt.localeCompare(b.createdAt)),threadClosed:false,threadId:thread,access:'full'};}
  if(route.startsWith('/messages'))return {items:[]};
  if(route==='/quotes'||route==='/documents')return {items:[]};
  throw Error('Ce document n’est pas disponible dans les données de démonstration.');
 }
 if(p==='/api/contacts'){if(method==='POST'){const c={...b,id:uid()};state.contacts??=[];state.contacts.push(c);save();return {contact:c};}return {page:1,totalPages:1,pageSize:100,totalCount:contacts().length,items:contacts().filter((c:any)=>(!u.searchParams.get('q')||c.name.toLowerCase().includes(u.searchParams.get('q')!.toLowerCase()))&&(!u.searchParams.get('kind')||u.searchParams.get('kind')!.split(',').includes(c.kind))&&(!['client','supplier'].includes(u.searchParams.get('type')||'')||c.type===u.searchParams.get('type')))};}
 if(p.startsWith('/api/contacts/')){
  const c=need(contacts().find((c:any)=>c.id===parts[3]));state.contactEdits??={};state.contactEdits[c.id]??={};const edit=state.contactEdits[c.id];
  if(parts[4]==='persons'){edit.contactPersons??=[];if(method==='POST')edit.contactPersons.push({...b,id:uid()});else if(method==='PATCH')Object.assign(need(edit.contactPersons.find((x:any)=>x.id===parts[5])),b);else if(method==='DELETE')edit.contactPersons=edit.contactPersons.filter((x:any)=>x.id!==parts[5]);else throw Error('Action non disponible');save();return {ok:true};}
  if(parts.length>4)throw Error('Cette action nécessite le service réel et reste désactivée dans la maquette.');
  if(method==='PATCH'){Object.assign(edit,b);save();}
  if(method==='DELETE'){if(db.worksites.some((w:any)=>w.client?.id===c.id))throw Error('Ce contact est utilisé par un chantier.');state.deletedContacts??=[];state.deletedContacts.push(c.id);save();return {ok:true};}
  const purchases=state.expenses.filter((e:any)=>e.contactId===c.id);
  return {contact:{...c,...edit,contactPersons:edit.contactPersons||[],worksites:db.worksites.filter((w:any)=>w.client?.id===c.id),purchases,purchaseBalance:[],purchaseSummary:{count:purchases.length,ht:purchases.reduce((s:number,e:any)=>s+e.ht,0),ttc:purchases.reduce((s:number,e:any)=>s+e.ttc,0),balance:purchases.filter((e:any)=>!e.paid).reduce((s:number,e:any)=>s+e.ttc,0)}}};
 }
 if(p==='/api/crm'||p.startsWith('/api/crm/')){
  state.opportunities??=[
   {id:'opp-demo-1',title:'Rénover une salle de bains',stage:'new',contactId:'c1',estimatedValue:18500,source:'Appel',nextActionOn:new Date().toISOString(),nextActionNote:'Préciser les attentes et convenir d’une visite',urgent:false,photos:[]},
   {id:'opp-demo-2',title:'Étanchéité des terrasses communes',stage:'to_qualify',contactId:'c0',estimatedValue:null,source:'Client existant',nextActionOn:null,nextActionNote:'Obtenir les plans et surfaces',urgent:false,photos:[]},
   {id:'opp-demo-3',title:'Finitions après réception · nouveau lot',stage:'quote_sent',contactId:'c2',estimatedValue:4200,source:'E-mail',nextActionOn:null,nextActionNote:'Attendre le retour sur le devis',urgent:false,photos:[]}
  ];
  const hydrate=(o:any)=>({note:null,problemType:null,unitLabel:null,onSiteContactName:null,onSiteContactPhone:null,accessNotes:null,visitPreference:null,...o,contact:contacts().find((c:any)=>c.id===o.contactId)||null,acp:contacts().find((c:any)=>c.id===o.acpId)||null});
  if(method==='POST'&&p==='/api/crm'){
   if(!b.title?.trim())throw Error('Indiquez l’objet de la demande.');
   if(b.stage&&!CRM_STAGES.includes(b.stage))throw Error('Étape invalide.');
   const opportunity={...b,id:uid(),stage:b.stage||'new',photos:[]};state.opportunities.push(opportunity);save();return {opportunity:hydrate(opportunity)};
  }
  if(method==='PATCH'&&parts.length===4){const opportunity=need(state.opportunities.find((o:any)=>o.id===parts[3]));if(b.stage&&!CRM_STAGES.includes(b.stage))throw Error('Étape invalide.');Object.assign(opportunity,b);save();return {opportunity:hydrate(opportunity)};}
  if(method!=='GET')throw Error('Cette action n’est pas connectée dans la démonstration.');
  return {columns:CRM_STAGES.filter(s=>s!=='won'&&s!=='lost').map(stage=>({stage,items:state.opportunities.filter((o:any)=>o.stage===stage).map(hydrate)}))};
 }
 if(p.startsWith('/api/documents')){
  const base=(kind='quote')=>({id:uid(),kind,number:null,draftRef:'DÉMO-'+((state.docs?.length||0)+1),status:'draft',source:'manual',title:'Travaux de remise en état',intro:null,terms:null,note:null,issuedOn:null,dueOn:null,validUntil:null,totalHt:0,totalVat:0,totalTtc:0,paidAmount:0,vatRate:null,structuredComm:null,peppolStatus:null,originalPdf:null,sentAt:null,acceptedOn:null,lockedAt:null,billingName:null,billingVat:null,billingAddress:null,billingEmail:null,customerRef:null,contact:contacts()[0],worksite:ws('w0'),parent:null,children:[],lines:[]});
  if(!state.docs){const lines=[{kind:'section',label:'Remise en état',qty:0,unitPriceHt:0,discountPct:0,vatRate:0},{kind:'item',label:'Préparation et peinture des supports',description:'Protection, préparation du support et deux couches de finition.',qty:32,unit:'m²',unitPriceHt:38,discountPct:0,vatRate:.21}];state.docs=[{...base(),id:'doc1',lines,...computeDocTotals(lines)},{...base('invoice'),id:'doc2',title:'Intervention · décompte',lines:[{kind:'item',label:'Main-d’œuvre intervention',qty:2,unit:'jour',unitPriceHt:500,discountPct:0,vatRate:.21}],...computeDocTotals([{kind:'item',qty:2,unitPriceHt:500,vatRate:.21}])}];}
  if(!state.dashboardDetailsV1){
   const date=new Date();date.setDate(1);const issuedOn=date.toISOString();
   for(const [i,status] of ['paid','overdue','partial','sent'].entries()){
    const lines=[{kind:'item',label:'Travaux de démonstration',qty:2,unit:'jour',unitPriceHt:500+i*100,discountPct:0,vatRate:.21}];
    const totals=computeDocTotals(lines);
    state.docs.push({...base('invoice'),id:'detail-invoice-'+i,number:'DÉMO-F-'+(101+i),status,issuedOn,lockedAt:issuedOn,dueOn:issuedOn,lines,...totals,paidAmount:status==='paid'?totals.totalTtc:status==='partial'?500:0});
   }
   state.docs.push({...base('quote'),id:'detail-quote',number:'DÉMO-D-101',status:'sent',issuedOn,lockedAt:issuedOn,lines:[{kind:'item',label:'Remise en état complète',qty:1,unit:'forfait',unitPriceHt:3600,discountPct:0,vatRate:.21}],totalHt:3600,totalVat:756,totalTtc:4356});
   state.dashboardDetailsV1=true;save();
  }
  if(p==='/api/documents'){
   if(method==='POST'){const d={...base(b.kind),worksite:b.worksiteId?ws(b.worksiteId):null,contact:b.contactId?contacts().find((c:any)=>c.id===b.contactId):null};state.docs.push(d);save();return {document:d};}
   const metric=u.searchParams.get('dashboard'),now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1);
   const items=state.docs.filter((d:any)=>{
    const kind=u.searchParams.get('kind');
    if(kind&&(kind==='invoice'?!['invoice','deposit_invoice'].includes(d.kind):d.kind!==kind))return false;
    if(u.searchParams.get('status')&&d.status!==u.searchParams.get('status'))return false;
    if(u.searchParams.get('worksiteId')&&d.worksite?.id!==u.searchParams.get('worksiteId'))return false;
    if(u.searchParams.get('q')&&!JSON.stringify(d).toLowerCase().includes(u.searchParams.get('q')!.toLowerCase()))return false;
    if(metric==='invoiced'||metric==='collected')return !!d.issuedOn&&new Date(d.issuedOn)>=start&&(metric!=='collected'||d.status==='paid');
    if(metric==='overdue')return d.status==='overdue';
    if(metric==='receivable')return ['sent','partial','overdue'].includes(d.status);
    if(metric==='quotes')return d.kind==='quote'&&d.status==='sent';
    return true;
   });return {items,page:1,pageSize:100,totalPages:1,totalCount:items.length};
  }
  const d=need(state.docs.find((d:any)=>d.id===parts[3]));if(parts.length===4){if(method==='PATCH'){Object.assign(d,b,{worksite:b.worksiteId?ws(b.worksiteId):null,contact:b.contactId?contacts().find((c:any)=>c.id===b.contactId):null});Object.assign(d,computeDocTotals(d.lines));save();}if(method==='DELETE'){state.docs=state.docs.filter((x:any)=>x.id!==d.id);save();return {ok:true};}return {document:d};}
  if(parts[4]==='duplicate'){const copy={...structuredClone(d),id:uid(),draftRef:'COPIE-DÉMO',number:null,status:'draft'};state.docs.push(copy);save();return {document:copy};}
  throw Error('Aucun envoi, émission officielle ou paiement réel depuis la maquette. Vous pouvez modifier et enregistrer le brouillon de démonstration.');
 }
 if(p==='/api/price-items')return {items:[{id:'price1',label:'Protection et préparation des supports',unit:'m²',unitPriceHt:12,vatRate:.21}]};
 if(p==='/api/worksites'&&method==='POST'){const building=b.buildingId?need(buildings().find((x:any)=>x.id===b.buildingId)):null;const worksite={...b,id:uid(),demoNew:true,ref:'DEMO-'+(101+db.worksites.length),status:b.status||'to_plan',entity:b.entity||'jjd',scope:b.scope||'intervention',quotedHt:Number(b.quotedHt)||0,invoicedHt:0,building:building?{id:building.id,name:building.name,photoThumbUrl:building.photoThumbUrl}:null,client:contacts().find((c:any)=>c.id===b.clientId)||null,manager:people.find((p:any)=>p.id===b.managerId)||null};db.worksites.push(worksite);localStorage.setItem('jjd-isolated-preview-v3',JSON.stringify(db));return worksite;}
 if(p==='/api/meta/pickers')return {worksites:db.worksites.map((w:any)=>({id:w.id,name:w.ref+' · '+w.title,clientId:w.client?.id,city:w.city})),clients:db.worksites.map((w:any)=>w.client),buildings:buildings().map((b:any)=>({id:b.id,name:b.name})),people:people.map(p=>({id:p.id,name:p.displayName})),syndics:[{id:'syndic1',name:'Syndic Démo'}],promoters:[{id:'promoter1',name:'Promoteur Démo'}]};
 if(p==='/api/buildings'&&method==='POST'){const building={...b,id:uid(),contacts:[],linkedContacts:[],units:[],worksites:[],_count:{worksites:0},photoUrl:null,photoThumbUrl:null,syndic:null,promoter:null};state.extraBuildings??=[];state.extraBuildings.push(building);save();return {building};}
 if(p==='/api/buildings')return {items:buildings().filter((b:any)=>!u.searchParams.get('q')||b.name.toLowerCase().includes(u.searchParams.get('q')!.toLowerCase()))};
 if(p.startsWith('/api/buildings/')){const id=parts[3];const build=need(buildings().find((x:any)=>x.id===id));const bucket=parts[4];if(bucket==='portal-users'||bucket==='portal-access'){state.portalUsers??={};state.portalUsers[id]??=[];if(method==='POST'){if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(b.email))throw Error('Adresse e-mail invalide.');if(state.portalUsers[id].some((x:any)=>x.email===b.email))throw Error('Cet accès figure déjà dans la simulation.');state.portalUsers[id].push({id:uid(),email:b.email,portalAccess:b.access,lastLoginAt:null});}if(method==='DELETE')state.portalUsers[id]=state.portalUsers[id].filter((x:any)=>x.id!==parts[5]);save();return {users:state.portalUsers[id],simulated:true};}if(bucket==='photo'){state.buildingEdits[id]={...state.buildingEdits[id],photoUrl:method==='DELETE'?null:b.photoData,photoThumbUrl:method==='DELETE'?null:b.photoData};save();return {ok:true};}if(['contacts','units'].includes(bucket)){const rows=build[bucket];if(method==='POST')rows.push({...b,id:uid(),contact:b.contactId?contacts().find((c:any)=>c.id===b.contactId)||null:null});else if(method==='PATCH')Object.assign(need(rows.find((r:any)=>r.id===parts[5])),b);else if(method==='DELETE')build[bucket]=rows.filter((r:any)=>r.id!==parts[5]);state.buildingEdits[id]={...state.buildingEdits[id],[bucket]:build[bucket]};save();return {ok:true};}if(method==='GET')return {building:{...build,contacts:(build.contacts||[]).map(currentPerson),units:(build.units||[]).map((r:any)=>({...r,contact:r.contactId?contacts().find((c:any)=>c.id===r.contactId)||null:null}))}};if(method==='PATCH'&&parts.length===4){state.buildingEdits[id]={...state.buildingEdits[id],...b};const extra=state.extraBuildings?.find((x:any)=>x.id===id);if(extra)Object.assign(extra,b);save();return {building:{...build,...b}};}throw Error('Suppression non disponible dans cet aperçu. Aucun dossier réel modifié.');}
 if(/^\/api\/worksites\/[^/]+$/.test(p)&&method==='GET'){
  const w=need(ws(parts[3]));const i=Math.max(0,db.worksites.indexOf(w));ensureTimeEntries(state,db,people,save);const labour=state.timeEntries.filter((e:any)=>e.worksiteId===w.id&&e.status!=='rejected').map((e:any)=>({date:e.date,personId:e.personId,personName:people.find(x=>x.id===e.personId)?.displayName||'Ouvrier',hours:e.hours,amount:e.amount,pending:e.status!=='approved'}));
  const margin=computeWorksiteMargin({entity:'jjd',quotedHt:w.quotedHt||0,invoicedHt:w.invoicedHt||0,paidHt:(w.invoicedHt||0)*.72,labourCost:labour.reduce((sum:number,r:any)=>sum+r.amount,0),materialCost:state.expenses.filter((e:any)=>e.worksiteId===w.id).reduce((sum:number,e:any)=>sum+e.ht,0),vehicleCost:240});
  return {worksite:{description:w.status==='on_hold'?'Après réparation de la fuite, séchage en cours. Contrôler l’humidité avant plafonnage et peinture.':'Protection des lieux, travaux prévus et remise en état. Consigner les photos et le rapport de fin de passage.',accessNotes:'Prendre rendez-vous avec la personne de contact avant le passage.',documents:[],reports:[],startedOn:'2026-09-21',events:db.events.filter((e:any)=>e.worksite?.id===w.id),...w,contacts:(w.contacts??[{id:'wc1',name:'Contact Démo',role:'locataire',phone:null,email:null,contactFor:'rdv_acces'}]).map((c:any,i:number)=>currentPerson({...c,id:c.id??`wc-${i}`}))},margin:{...margin,labour,transport:{cost:240,fuelCost:140,fixedCost:100,note:'Données fictives',oneWayKm:18,trips:[]}},activity:[{id:'act1',label:'Dossier créé',by:'Melvina',at:'2026-09-21T08:00:00Z'}]};
 }
 if(p==='/api/stock/meta')return {worksites:db.worksites.map((w:any)=>({id:w.id,name:`${w.ref} · ${w.title}`})),categories:['Finitions'],suppliers:[contact],contacts:[contact]};
 if(p==='/api/stock/items'){
  if(method==='POST'){const item={...structuredClone(state.stock[0]),...b,id:uid(),qty:0,value:0,barcodes:[],suppliers:[],units:b.units||[]};state.stock.push(item);save();return {item};}
  return {items:state.stock.filter((i:any)=>!u.searchParams.get('q')||`${i.name} ${i.ref}`.toLowerCase().includes(u.searchParams.get('q')!.toLowerCase()))};
 }
 if(p.startsWith('/api/stock/items/')){const item=need(state.stock.find((i:any)=>i.id===parts[4]));if(parts[5]==='purchase-history')return {items:[]};if(method==='PATCH'){Object.assign(item,b);save();return {item};}if(method==='GET')return {item};throw Error('Modification avancée non disponible dans les données de test.');}
 if(p.startsWith('/api/stock/scan/')){const code=decodeURIComponent(parts[4]);const item=need(state.stock.find((i:any)=>i.barcodes.some((bc:any)=>bc.code.toLowerCase()===code.toLowerCase())));return {item,unitName:null};}
 if(p==='/api/stock/movements'){if(method==='GET')return {items:state.moves.filter((m:any)=>!u.searchParams.get('stockItemId')||m.stockItem.id===u.searchParams.get('stockItemId')),page:1,totalPages:1};const item=need(state.stock.find((i:any)=>i.id===b.stockItemId));const qty=Number(b.qty);if(!Number.isFinite(qty)||qty<=0)throw Error('Quantité invalide');if(b.type==='out'&&qty>item.qty)throw Error('Stock insuffisant');movement(item,b.type==='out'?-qty:qty,b.note||'Mouvement manuel',b.worksiteId);save();return {ok:true};}
 for(const [prefix,field] of [['/api/stock-orders','preps'],['/api/purchasing/orders','orders']]){
  if(p===prefix){if(method==='POST'){const o={...b,id:uid(),ref:`${field==='preps'?'PREP':'CF'}-${state[field].length+1}`,status:b.status||(field==='preps'?'to_prepare':'draft'),lines:b.lines.map((l:any)=>({...l,id:uid(),pickedQty:0,receivedQty:0}))};state[field].push(o);save();return {order:orderView(o)};}const status=u.searchParams.get('status');return {items:state[field].filter((o:any)=>status==='open'?!['prepared','received','cancelled'].includes(o.status):status==='prepared'?o.status==='prepared':status==='closed'?['received','cancelled'].includes(o.status):true).map(orderView)};}
  if(p.startsWith(prefix+'/')){const rest=p.slice(prefix.length+1).split('/');const o=need(state[field].find((o:any)=>o.id===rest[0]));if(method==='GET')return {order:orderView(o)};
   if(['prepared','received','cancelled'].includes(o.status))throw Error('Cette commande est déjà clôturée.');
   if(rest[1]==='scan'){const item=need(state.stock.find((i:any)=>i.barcodes.some((bc:any)=>bc.code.toLowerCase()===b.code.toLowerCase())));const line=need(o.lines.find((l:any)=>l.stockItemId===item.id));if(line.pickedQty>=Math.min(line.qty,item.qty))throw Error('Quantité demandée atteinte ou stock insuffisant');line.pickedQty++;o.status='preparing';save();return {order:orderView(o),itemName:item.name};}
   if(rest[1]==='lines'&&rest[3]==='picked'){const line=need(o.lines.find((l:any)=>l.id===rest[2]));const item=need(state.stock.find((i:any)=>i.id===line.stockItemId));if(!Number.isFinite(b.pickedQty)||b.pickedQty<0||b.pickedQty>Math.min(line.qty,item.qty))throw Error('Quantité préparée invalide ou stock insuffisant');line.pickedQty=b.pickedQty;o.status='preparing';}
   else if(rest[1]==='complete'){if(o.lines.some((l:any)=>l.pickedQty<l.qty)&&!b.allowShort)throw Error('Confirmez la préparation partielle');for(const l of o.lines){const item=need(state.stock.find((i:any)=>i.id===l.stockItemId));if(l.pickedQty>item.qty)throw Error('Stock insuffisant');}o.lines.forEach((l:any)=>{if(l.pickedQty)movement(state.stock.find((i:any)=>i.id===l.stockItemId),-l.pickedQty,`Préparation ${o.ref}`,o.worksiteId)});o.status='prepared';o.preparedAt=new Date().toISOString();}
   else if(rest[1]==='receive'){for(const l of b.lines){const line=need(o.lines.find((x:any)=>x.id===l.lineId));if(!Number.isFinite(l.qty)||l.qty<=0||l.qty>line.qty-line.receivedQty)throw Error('Quantité reçue invalide');}b.lines.forEach((l:any)=>{const line=o.lines.find((x:any)=>x.id===l.lineId);line.receivedQty+=l.qty;movement(state.stock.find((i:any)=>i.id===line.stockItemId),l.qty,`Réception ${o.ref}`,o.worksiteId)});o.status=o.lines.every((l:any)=>l.receivedQty>=l.qty)?'received':'partial';}
   else if(rest[1]==='cancel')o.status='cancelled';else if(rest[1]==='order')o.status='ordered';
   save();return {order:orderView(o)};
  }
 }
 // Real finance screens, using isolated examples only.
 if(p==='/api/ponto/status')return {configured:false,connected:false,redirectUri:'',accounts:[]};
 if(p==='/api/finance/years')return {years:[2026]};
 if(p==='/api/finance/consolidated'){
  const revenue=(state.docs||[]).filter((d:any)=>d.kind==='invoice'&&d.lockedAt).reduce((sum:number,d:any)=>sum+d.totalHt,0);
  const expenses=state.expenses.reduce((sum:number,e:any)=>sum+e.ht,0);
  return {revenue:{total:revenue,net:revenue,creditNotes:0,byEntity:{jjd:revenue}},expenses:{total:expenses,sections:[{key:'materials',label:'Achats de démonstration',total:expenses,lines:[{label:'Matériaux',amount:expenses}]}]},labour:0,result:revenue-expenses,margin:revenue?(revenue-expenses)/revenue:null};
 }
 if(p==='/api/finance/ledger-sync/gaps')return {items:[],missingCount:0,matchableCount:0};
 if(p.startsWith('/api/finance/bank')){
  state.bank??=state.expenses.slice(0,2).map((e:any,i:number)=>({id:'bank-demo-'+i,bookingDate:'2026-09-29',bank:i?'ING':'Belfius',counterpartyName:e.supplierName,description:'Paiement de démonstration',amount:-e.ttc,communication:e.docNumber,matchConfidence:i?null:'manual',matches:i?[]:[{id:'bank-match-1',ledgerEntry:e,document:null}]}));
  const hydrateBank=(t:any)=>({...t,matches:t.matches.map((m:any)=>({...m,ledgerEntry:m.ledgerEntry?state.expenses.find((e:any)=>e.id===m.ledgerEntry.id):null}))});
  if(p==='/api/finance/bank'&&method==='GET'){
   const items=state.bank.map(hydrateBank).filter((t:any)=>(u.searchParams.get('matched')==='0'?!t.matches.length:u.searchParams.get('matched')==='1'?!!t.matches.length:true)&&(!u.searchParams.get('bank')||t.bank===u.searchParams.get('bank'))&&(!u.searchParams.get('q')||JSON.stringify(t).toLowerCase().includes(u.searchParams.get('q')!.toLowerCase())));
   return {items,total:state.bank.length,matched:state.bank.filter((t:any)=>t.matches.length).length,byBank:['Belfius','ING'].map(bank=>({bank,_count:1})),page:1,totalPages:1,totalCount:items.length};
  }
  const t=need(state.bank.find((t:any)=>t.id===parts[4]));
  if(parts[5]==='suggestions')return {remaining:Math.abs(t.amount)-t.matches.reduce((sum:number,m:any)=>sum+(m.ledgerEntry?.ttc||0),0),items:state.expenses.filter((e:any)=>!state.bank.some((tx:any)=>tx.matches.some((m:any)=>m.ledgerEntry?.id===e.id))).map((e:any)=>({id:e.id,kind:'ledger',label:e.docNumber+' · '+e.supplierName,amount:e.ttc,date:e.date,direction:'purchase',worksiteRef:e.worksite?.ref}))};
  if(parts[5]==='matches'&&method==='POST'){const e=need(state.expenses.find((e:any)=>e.id===b.ledgerId));if(state.bank.some((tx:any)=>tx.matches.some((m:any)=>m.ledgerEntry?.id===e.id)))throw Error('Cette dépense est déjà rapprochée.');t.matches.push({id:uid(),ledgerEntry:e,document:null});t.matchConfidence='manual';e.paid=true;e.paymentStatus='paid';save();return {ok:true};}
  if(parts[5]==='matches'&&method==='DELETE'){const m=need(t.matches.find((m:any)=>m.id===parts[6]));const e=state.expenses.find((e:any)=>e.id===m.ledgerEntry?.id);if(e){e.paid=false;e.paymentStatus='unpaid';}t.matches=t.matches.filter((m:any)=>m.id!==parts[6]);save();return {ok:true};}
  throw Error('Import ou connexion bancaire indisponible dans cet aperçu isolé.');
 }
 if(p==='/api/finance/expenses/meta')return {categories:[{code:'materials',label:'Matériaux',kind:'purchase'}],rawCategories:['Matériaux'],suppliers:[contact],worksites:db.worksites.map((w:any)=>({id:w.id,name:w.ref+' · '+w.title})),vehicles:[],years:[2026]};
 if(p==='/api/finance/expenses/mailbox-status')return {configured:false};
 if(p==='/api/finance/expenses'){
  if(method==='POST'){const e={...state.expenses[0],...b,id:uid(),hasPdf:false,worksite:b.worksiteId?ws(b.worksiteId):null};state.expenses.push(e);save();return {expense:e};}
  const items=state.expenses.filter((e:any)=>(u.searchParams.get('overdue')!=='1'||(e.direction==='purchase'&&!e.paid&&e.dueDate&&new Date(e.dueDate)<new Date()))&&(!u.searchParams.get('worksiteId')||e.worksiteId===u.searchParams.get('worksiteId'))&&(!u.searchParams.get('q')||JSON.stringify(e).toLowerCase().includes(u.searchParams.get('q')!.toLowerCase()))&&(!u.searchParams.get('paid')||e.paid===(u.searchParams.get('paid')==='1')));return {items,totals:{count:items.length,ht:items.reduce((s:number,e:any)=>s+e.ht,0),ttc:items.reduce((s:number,e:any)=>s+e.ttc,0),unpaidTtc:items.filter((e:any)=>!e.paid).reduce((s:number,e:any)=>s+e.ttc,0),pendingSlips:0,overdueCount:0,overdueTtc:0},page:1,pageSize:100,totalPages:1};
 }
 if(p.startsWith('/api/finance/expenses/')){const e=need(state.expenses.find((e:any)=>e.id===parts[4]));if(p.endsWith('/bank-suggestions'))return {items:[]};if(p.endsWith('/paid')){e.paid=b.paid;e.paymentStatus=b.paid?'paid':'unpaid';}else if(method==='PATCH')Object.assign(e,b,{worksite:b.worksiteId?ws(b.worksiteId):e.worksite});else if(method==='DELETE')state.expenses=state.expenses.filter((x:any)=>x.id!==e.id);save();return {expense:{...e,bankMatches:[]}};}

 if(p.startsWith('/api/stock/locations')){state.racks??=['A-02','B-01'];if(method==='POST')state.racks=[...new Set([...state.racks,...b.codes])];if(method==='DELETE')state.racks=state.racks.filter((c:string)=>c!==decodeURIComponent(parts[4]));save();return {items:state.racks.map((code:string)=>({code,id:code,label:null,itemCount:state.stock.filter((x:any)=>x.location===code).length}))};}
 if(p.startsWith('/api/materiel/')){
  state.tools??=[{id:'tool1',slug:'perforateur',name:'Perforateur',image:'/demo/jjd/rotary-hammer.png',kind:'MACHINE',category:'Perçage',brand:null,model:null,specs:{},documents:[],units:[{assetTag:'MAT-001',state:'AVAILABLE',storageLocation:'A-01',chantier:null}]},{id:'tool2',slug:'laser',name:'Laser de chantier',image:'/demo/jjd/laser.png',kind:'MACHINE',category:'Mesure',brand:null,model:null,specs:{},documents:[],units:[{assetTag:'MAT-002',state:'ON_SITE',storageLocation:null,chantier:{name:ws('w1')?.title,ref:'DEMO-102',since:'2026-09-29'}}]}];
  if(p.endsWith('/status'))return {enabled:true};
  if(p.endsWith('/worksites'))return {items:db.worksites};
  if(p.endsWith('/consumables'))return {consumables:[]};
  if(p.endsWith('/stock'))return {products:state.tools.map((t:any)=>({...t,total:t.units.length,available:t.units.filter((x:any)=>x.state==='AVAILABLE').length,onSite:t.units.filter((x:any)=>x.state==='ON_SITE').length,rented:0}))};
  const code=p.includes('/units/')?decodeURIComponent(parts[4]):b?.code;const product=need(state.tools.find((t:any)=>t.units.some((x:any)=>x.assetTag===code)));const unit=product.units.find((x:any)=>x.assetTag===code);
  if(p.includes('/units/'))return {unit,product};
  if(p.endsWith('/loans')){if(unit.state!=='AVAILABLE')throw Error('Cet outil est déjà affecté.');const w=need(ws(b.worksiteId));unit.state='ON_SITE';unit.storageLocation=null;unit.chantier={name:w.title,ref:w.ref,since:new Date().toISOString()};}
  if(p.endsWith('/returns')){if(unit.state!=='ON_SITE')throw Error('Cet outil est déjà au dépôt.');if(!b.storageLocation?.trim())throw Error('Précisez le rangement au dépôt.');unit.state='AVAILABLE';unit.storageLocation=b.storageLocation;unit.chantier=null;}
  save();return {ok:true};
 }
 if(/^\/api\/worksites\/[^/]+\/(tasks|phases)$/.test(p)) {const bucket=parts[4];state[bucket]??={};state[bucket][parts[3]]??=bucket==='tasks'?[{id:'t-'+parts[3],title:'Contrôler et préparer le prochain passage',status:'todo',phaseId:null,assignees:[],description:null,dueOn:null}]:[];const rows=state[bucket][parts[3]];if(method==='POST'){const row={...b,id:uid(),status:'todo',assignees:(b.assigneeIds||[]).map((id:string)=>({id,name:people.find(x=>x.id===id)?.displayName||id}))};rows.push(row);save();return row;}return {items:rows};}
 if(/^\/api\/(tasks|phases)\//.test(p)){const rows=Object.values(state[parts[2]]||{}).flat() as any[];const row=need(rows.find(x=>x.id===parts[3]));if(method==='DELETE'){for(const key of Object.keys(state[parts[2]]))state[parts[2]][key]=state[parts[2]][key].filter((x:any)=>x.id!==row.id);}else Object.assign(row,b);save();return row;}
 if(p.startsWith('/api/worksites/')&&p.includes('/thread')){const threadKey=parts[3]+(p.includes('/client')?'-client':'-internal');state.threads[threadKey]??=[{id:'welcome-'+threadKey,kind:'text',body:p.includes('/client')?'Votre demande est prise en charge. Nous vous confirmerons le prochain passage.':'Les photos et consignes de ce chantier sont regroupées ici.',authorName:'Melvina',createdAt:'2026-09-29T08:00:00Z',fileUrl:null,thumbUrl:null}];const messages=state.threads[threadKey];if(method==='POST'&&p.endsWith('/messages')){messages.push({id:uid(),kind:'text',body:b.body,authorName:'David',authorId:'demo',createdAt:new Date().toISOString()});save();}return {thread:{id:threadKey,closedAt:null},messages,participants:people.slice(0,4)};}
 if(p==='/api/purchasing/catalog/suppliers')return {items:[{...contact,count:3}]};
 if(p==='/api/purchasing/catalog')return {items:[],total:0};
 if(p==='/api/tasks')return {items:state.tasks[u.searchParams.get('worksiteId')||'']||[]};
 return undefined;
}
