import { vehicleCostPerKm } from '@jjd/shared';
const key = 'jjd-fleet-preview-v1';
const blank = () => ({ brand: '', model: '', plate: '', code: '', type: 'Camionnette', seats: null, status: 'active', excludedFromPlanning: false, fuel: null, driver: null, depot: 'Ruisbroek', photoUrl: null, photoThumbUrl: null, km: null, vin: null, firstRegistration: null, nextInspection: null, circulationTax: null, biv: null, equipment: null, note: null, acquisitionMode: null, purchaseDate: null, purchasePriceHt: null, financedAmount: null, monthlyPayment: null, downPayment: null, residualValue: null, financeMonths: null, financeEndOn: null, financeCompany: null, financeContract: null, fuelConsoL100: null, fuelPricePerL: null, costPerKmExtra: null, parkingMonthly: null, otherMonthly: null, insurances: [], fines: [], payments: [], docs: [], repairs: [], ledgerEntries: [] });
let saved: any;try { saved = JSON.parse(localStorage.getItem(key) || 'null'); } catch {}
export const vehicles: any[] = saved || Array.from({ length: 6 }, (_, i) => ({ ...blank(), id: 'v'+i, code: 'V'+(i+1), plate: 'DEMO-'+(i+1), brand: i%2 ? 'Ford' : 'Renault', model: i%2 ? 'Transit' : 'Trafic', seats: i===0 ? 3 : 6, fuel: 'Diesel', photoUrl: '/demo/jjd/van.png', photoThumbUrl: '/demo/jjd/van.png', driver: ['José','André','Bruno',null,null,null][i], km: String(42000+i*11000), nextInspection: new Date(Date.now()+(i===0?12:70+i*20)*86400000).toISOString(), fuelConsoL100: 8.5, fuelPricePerL: 1.7, costPerKmExtra: .06, monthlyPayment: 420, acquisitionMode: 'Leasing · démonstration', insurances: [{ provider: 'Assureur Démo', monthlyAmount: 75, annualAmount: null, contractNumber: 'ASS-DEMO-'+i, paymentMode: 'Mensuel' }], repairs: i===0 ? [{ id: 'repair-demo', date: '2026-09-15', description: 'Entretien périodique', garage: 'Garage Démo', amount: 285, km: '41500' }] : [], docs: [{ id: 'doc-demo-'+i, type: 'inspection', label: 'Contrôle technique · exemple', number: 'CT-DEMO-'+i, expiresOn: new Date(Date.now()+(i===0?12:70+i*20)*86400000).toISOString(), fileUrl: null }], fines: i===1 ? [{ id: 'fine-demo', date: '2026-09-22', reference: 'PV-DÉMO', type: 'Stationnement', amount: 35, status: 'Impayé', payTo: 'Commune · exemple' }] : [] }));
function save() { localStorage.setItem(key, JSON.stringify(vehicles)); }
export function resetFleet() { localStorage.removeItem(key); }
const find = (id: string) => { const v = vehicles.find(v => v.id === id); if (!v) throw Error('Véhicule introuvable.'); return v; };
export function fleetApi(path: string, method: string, b: any): any {
  const url = new URL(path, 'https://demo.invalid'); const p = url.pathname.split('/');
  if(p[2] !== 'vehicles') return undefined;
  const view = (v: any) => { const insurance = v.insurances.reduce((s: number, r: any) => s + (r.monthlyAmount ?? (r.annualAmount ?? 0)/12), 0); const financing=v.monthlyPayment??0, tax=(v.circulationTax??0)/12+(v.biv??0)/60, parking=v.parkingMonthly??0, other=v.otherMonthly??0, monthly=insurance+financing+tax+parking+other; return {...v,_count:{fines:v.fines.length,payments:v.payments.length},costPerKm:vehicleCostPerKm(v),costBreakdown:{fuelPerKm:vehicleCostPerKm(v),workDaysPerYear:220,fixed:{insurance,financing,tax,parking,other,monthly,perDay:monthly*12/220}}}; };
  if(p[3]==='fines') return {items:vehicles.flatMap(v=>v.fines.filter((f:any)=>!url.searchParams.get('unpaid')||f.status!=='Payé').map((f:any)=>({...f,vehicle:{id:v.id,brand:v.brand,model:v.model,photoThumbUrl:v.photoThumbUrl},plateRaw:v.plate})))};
  if(p.length===3){ if(method==='GET')return {items:vehicles.map(view)}; if(method==='POST'){const v={...blank(),...b,id:crypto.randomUUID()};if(v.seats!=null&&(!Number.isInteger(Number(v.seats))||Number(v.seats)<1))throw Error('Le nombre de places doit être un entier positif.');vehicles.push(v);save();return {vehicle:view(v)};} }
  const v=find(p[3]);
  if(p.length===4){if(method==='PATCH'){if(b.seats!=null&&(!Number.isInteger(Number(b.seats))||Number(b.seats)<1))throw Error('Le nombre de places doit être un entier positif.');Object.assign(v,b);save();}return {vehicle:view(v)};}
  if(p[4]==='photo'){v.photoUrl=method==='DELETE'?null:b.photoData;v.photoThumbUrl=v.photoUrl;save();return {ok:true};}
  if(['docs','repairs'].includes(p[4])){const rows=v[p[4]];if(p[6]==='file'){const doc=rows.find((r:any)=>r.id===p[5]);if(!doc)throw Error('Document introuvable.');doc.fileUrl=b.fileData;save();return {doc};}if(method==='POST'){const row={...b,id:crypto.randomUUID(),...(p[4]==='docs'?{fileUrl:null}:{})};rows.push(row);save();return p[4]==='docs'?{doc:row}:{repair:row};}const row=rows.find((r:any)=>r.id===p[5]);if(!row)throw Error('Élément introuvable.');if(method==='PATCH')Object.assign(row,b);else if(method==='DELETE')v[p[4]]=rows.filter((r:any)=>r.id!==p[5]);save();return {ok:true};}
  throw Error('Cette action n’est pas disponible dans la maquette.');
}
export function fleetDocument(path: string): string {
 const p=path.split('/');const doc=find(p[3]).docs.find((d:any)=>d.id===p[5]);if(!doc?.fileUrl)throw Error('Aucun fichier joint.');const [header,data]=doc.fileUrl.split(',');const mime=header.match(/^data:([^;]+);base64$/)?.[1];if(!mime||!['application/pdf','image/png','image/jpeg','image/webp'].includes(mime))throw Error('Format de document invalide.');return URL.createObjectURL(new Blob([Uint8Array.from(atob(data),c=>c.charCodeAt(0))],{type:mime}));
}
