import FleetPage from '../apps/web/src/app/app/flotte/page';
import FleetDetail from '../apps/web/src/app/app/flotte/[id]/page';
import FleetFines from '../apps/web/src/app/app/flotte/pv/page';
import React, {Suspense,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import BankPage from '../apps/web/src/app/app/finances/banque/page';
import FinancesPage from '../apps/web/src/app/app/finances/page';
import LedgerPage from '../apps/web/src/app/app/finances/grand-livre/page';
import ExpensesPage from '../apps/web/src/app/app/achats/page';
import DocumentsPage from '../apps/web/src/app/app/documents/page';
import DocumentPage from '../apps/web/src/app/app/documents/[id]/page';
import WorksitePage from '../apps/web/src/app/app/chantiers/[id]/page';
import BuildingsPage from '../apps/web/src/app/app/immeubles/page';
import BuildingPage from '../apps/web/src/app/app/immeubles/[id]/page';
import RacksPage from '../apps/web/src/app/app/stock/racks/page';
import TariffsPage from '../apps/web/src/app/app/stock/tarifs/page';
import ScanPage from '../apps/web/src/app/app/stock/scan/page';
import EquipmentPage from '../apps/web/src/app/app/materiel/page';
import EquipmentDetail from '../apps/web/src/app/app/materiel/[id]/page';
import StockPage from '../apps/web/src/app/app/stock/page';
import StockDetail from '../apps/web/src/app/app/stock/[id]/page';
import PreparationsPage from '../apps/web/src/app/app/stock/preparations/page';
import PreparationPage from '../apps/web/src/app/app/stock/preparations/[id]/page';
import OrdersPage from '../apps/web/src/app/app/stock/commandes/page';
import OrderPage from '../apps/web/src/app/app/stock/commandes/[id]/page';
import {DepotFrame} from '../apps/web/src/components/DepotFrame';
import PortalBuildings from '../apps/web/src/app/portail/immeubles/page';
import PortalBuilding from '../apps/web/src/app/portail/immeuble/[id]/page';
import PortalWorksite from '../apps/web/src/app/portail/chantier/[id]/page';
import PortalRequest from '../apps/web/src/app/portail/demande/page';
import PortalHome from '../apps/web/src/app/portail/accueil/page';
import PortalInterventions from '../apps/web/src/app/portail/interventions/page';
import PortalPlanning from '../apps/web/src/app/portail/planning/page';
import PortalDocuments from '../apps/web/src/app/portail/documents/page';
import PortalQuotes from '../apps/web/src/app/portail/devis/page';
import PortalMessages from '../apps/web/src/app/portail/messages/page';
import PortalLayout from '../apps/web/src/app/portail/layout';
import {Shell} from '../apps/web/src/components/Shell';
import Dashboard from '../apps/web/src/app/app/page';
import TasksPage from '../apps/web/src/app/app/taches/page';
import PointagePage from '../apps/web/src/app/app/pointage/page';
import StatementsPage from '../apps/web/src/app/app/pointage/decomptes/page';
import StatementsPrint from '../apps/web/src/app/imprimer/decomptes/page';
import CrmPage from '../apps/web/src/app/app/crm/page';
import Planning from '../apps/web/src/app/app/planning/page';
import Chantiers from '../apps/web/src/app/app/chantiers/page';
import {usePathname} from './navigation';
import {getWorksite,reset} from './api';
import ContactsPage from '../apps/web/src/app/app/contacts/page';
import ContactPage from '../apps/web/src/app/app/contacts/[id]/page';
import TeamPage from '../apps/web/src/app/app/equipe/page';
import PersonPage from '../apps/web/src/app/app/equipe/[id]/page';
import AnalysePage from '../apps/web/src/app/app/analyse/page';
import ControlePage from '../apps/web/src/app/app/controle/page';
import MessagingPage from '../apps/web/src/app/app/messagerie/page';
import '../apps/web/src/app/globals.css';

function App(){
  const path=usePathname();
  const id=path.split('/').pop()!;
  const params=useMemo(()=>Promise.resolve({id}),[id]);
  const ws=path.startsWith('/app/chantiers/')?getWorksite(id):null;
  let business:React.ReactNode=null;
  if(path==='/imprimer/decomptes')return <><p className="no-print" style={{padding:16}}>Décompte de démonstration — données fictives</p><StatementsPrint/></>;
  if(path==='/app/contacts')business=<ContactsPage/>;
  else if(path==='/app/taches')business=<TasksPage/>;
  else if(path==='/app/pointage')business=<PointagePage/>;
  else if(path==='/app/pointage/decomptes')business=<StatementsPage/>;
  else if(path==='/app/crm')business=<CrmPage/>;
  else if(path.startsWith('/app/contacts/'))business=<ContactPage key={id} params={params}/>;
  else if(path==='/app/equipe')business=<TeamPage/>;
  else if(path.startsWith('/app/equipe/'))business=<PersonPage key={id} params={params}/>;
  else if(path==='/app/analyse')business=<AnalysePage/>;
  else if(path==='/app/controle')business=<ControlePage/>;
  else if(path==='/app/finances/banque')business=<BankPage/>;
  else if(path==='/app/finances')business=<FinancesPage/>;
  else if(path==='/app/finances/grand-livre')business=<LedgerPage/>;
  else if(path==='/app/achats')business=<ExpensesPage/>;
  else if(path==='/app/documents')business=<DocumentsPage/>;
  else if(path.startsWith('/app/documents/'))business=<DocumentPage key={id} params={params}/>;
  else if(path==='/app/immeubles')business=<BuildingsPage/>;
  else if(path.startsWith('/app/immeubles/'))business=<BuildingPage key={id} params={params}/>;
  else if(path==='/app/stock')business=<StockPage/>;
  else if(path==='/app/stock/preparations')business=<PreparationsPage/>;
  else if(path.startsWith('/app/stock/preparations/'))business=<PreparationPage key={id} params={params}/>;
  else if(path==='/app/stock/commandes')business=<OrdersPage/>;
  else if(path.startsWith('/app/stock/commandes/'))business=<OrderPage key={id} params={params}/>;
  else if(path==='/app/stock/racks')business=<RacksPage/>;
  else if(path==='/app/stock/tarifs')business=<TariffsPage/>;
  else if(path==='/app/stock/scan')business=<ScanPage/>;
  else if(path.startsWith('/app/stock/'))business=<StockDetail key={id} params={params}/>;
  if(path==='/app/flotte')business=<FleetPage/>;
  else if(path==='/app/flotte/pv')business=<FleetFines/>;
  else if(path.startsWith('/app/flotte/'))business=<FleetDetail key={id} params={params}/>;
  if(path==='/app/materiel')business=<EquipmentPage/>;
  else if(path.startsWith('/app/materiel/'))business=<EquipmentDetail key={id} params={params}/>;
  if((path.startsWith('/app/stock')||path.startsWith('/app/materiel'))&&business)business=<DepotFrame>{business}</DepotFrame>;
  if(path.startsWith('/portail')){const page=path==='/portail/immeubles'?<PortalBuildings/>:path.startsWith('/portail/immeuble/')?<PortalBuilding key={id} params={params}/>:path.startsWith('/portail/chantier/')?<PortalWorksite key={id} params={params}/>:path==='/portail/demande'?<PortalRequest/>:path==='/portail/interventions'?<PortalInterventions/>:path==='/portail/planning'?<PortalPlanning/>:path==='/portail/documents'?<PortalDocuments/>:path==='/portail/devis'?<PortalQuotes/>:path==='/portail/messages'?<PortalMessages/>:<PortalHome/>;return <><div className="preview-ribbon"><strong>Portail client · données fictives</strong><a href="#/app/immeubles">Retour administration</a><select aria-label="Profil client de démonstration" value={localStorage.getItem('jjd-preview-client-profile')||'syndic'} onChange={e=>{localStorage.setItem('jjd-preview-client-profile',e.target.value);location.hash='/portail/immeubles';location.reload();}}><option value="syndic">Syndic</option><option value="promoter">Promoteur</option><option value="private">Particulier</option><option value="resident">Résident</option></select></div><PortalLayout><Suspense fallback={<p>Chargement…</p>}>{page}</Suspense></PortalLayout></>;}
  const navigationPaths=['/app','/app/chantiers','/app/planning','/app/taches','/app/crm','/app/messagerie','/app/documents','/app/achats','/app/analyse','/app/finances','/app/immeubles','/app/contacts','/app/equipe','/app/flotte','/app/controle','/app/stock','/app/stock/preparations','/app/stock/commandes','/app/stock/scan','/app/materiel'];
  const known=navigationPaths.includes(path)||!!ws;
  navigationPaths.push('/app/pointage');
  return <><div className="preview-ribbon"><strong>Aperçu privé · données fictives</strong><span>Écrans du site · visuel de la maquette validée</span><a href="#/portail/immeubles">Tester le portail client</a><select aria-label="Profil interne de démonstration" value={localStorage.getItem('jjd-preview-staff-profile')||'admin'} onChange={e=>{localStorage.setItem('jjd-preview-staff-profile',e.target.value);location.hash='/app';location.reload();}}><option value="admin">Administration</option><option value="office">Bureau</option><option value="foreman">Chef de chantier</option><option value="worker">Ouvrier</option><option value="storekeeper">Magasinier</option></select><button onClick={()=>{if(confirm('Réinitialiser uniquement les données fictives de cet aperçu ?'))reset()}}>Réinitialiser</button></div><Shell navigationPaths={navigationPaths}><Suspense fallback={<div className="state">Chargement de la fiche…</div>}>{business??(path==='/app'?<Dashboard/>:path==='/app/chantiers'?<Chantiers/>:ws?<WorksitePage key={id} params={params}/>:path==='/app/planning'?<Planning/>:path==='/app/messagerie'?<MessagingPage/>:<section className="state"><h2>Parcours en préparation</h2><p>Cette page annexe sera reprise dans la prochaine étape de la maquette.</p><a className="btn primary" href="#/app">Retour à la vue d’ensemble</a></section>)}</Suspense>{!known&&null}</Shell></>;
}

createRoot(document.getElementById('root')!).render(<App/>);
