import { build } from 'esbuild';
import { createRequire } from 'node:module';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const dir = await mkdtemp(path.join(tmpdir(), 'jjd-fleet-check-'));
try {
 await build({ entryPoints:['preview/api.ts'], bundle:true, platform:'node', format:'cjs', outfile:path.join(dir,'api.cjs') });
 const data={};globalThis.localStorage={getItem:k=>data[k]||null,setItem:(k,v)=>data[k]=v,removeItem:k=>delete data[k]};
 const require=createRequire(import.meta.url), file=path.join(dir,'api.cjs');
 let {api}=require(file);
 const original=await api('/api/vehicles');assert.equal(original.items.length,6);assert.equal(original.items[0].seats,3);
 const {vehicle}=await api('/api/vehicles',{method:'POST',body:{brand:'Test',model:'Fourgon',seats:5,status:'active',excludedFromPlanning:false}});
 assert((await api('/api/vehicles')).items.some(v=>v.id===vehicle.id));
 await assert.rejects(()=>api('/api/vehicles/'+vehicle.id,{method:'PATCH',body:{seats:-1}}));
 const event=await api('/api/planning',{method:'POST',body:{worksiteId:'w0',startAt:'2026-10-01T07:00:00Z',endAt:'2026-10-01T12:00:00Z',personIds:['p0'],vehicles:[{vehicleId:vehicle.id,driverPersonId:'p0'}]}});
 await api('/api/vehicles/'+vehicle.id,{method:'PATCH',body:{seats:4,status:'repair'}});
 const updated=(await api('/api/planning')).items.find(e=>e.id===event.id);assert.equal(updated.vehicles[0].vehicle.seats,4);assert.equal(updated.vehicles[0].vehicle.status,'repair');
 const base='/api/vehicles/'+vehicle.id;
 await api(base+'/repairs',{method:'POST',body:{description:'Test entretien',amount:100}});
 const {doc}=await api(base+'/docs',{method:'POST',body:{type:'inspection',label:'Test contrôle'}});
 await api(base+'/docs/'+doc.id+'/file',{method:'POST',body:{fileData:'data:application/pdf;base64,JVBERi0xLjQ='}});
 const detail=(await api(base)).vehicle;assert.equal(detail.repairs.length,1);assert(detail.docs[0].fileUrl);
 delete require.cache[file];api=require(file).api;
 assert.equal((await api(base)).vehicle.seats,4);assert.equal((await api(base)).vehicle.repairs[0].amount,100);
 await api(base+'/docs/'+doc.id,{method:'DELETE'});assert.equal((await api(base)).vehicle.docs.length,0);
 assert.equal((await api('/api/vehicles/fines?unpaid=1')).items.length,1);
 console.log('PASS: fleet create/edit, planning consistency, repairs, document persistence, fines, reload.');
} finally { await rm(dir,{recursive:true,force:true}); }
